on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

env:
  PASS: "garageWoder_2024"

jobs:
  # deploy Fe to server
  deploy-fe:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v4
     
     - name: Setup Node
       uses: actions/setup-node@v2
       with:
         node-version: '20.x'

     - name: Build FE App
       run: | 
         npm i
         npm i @rollup/rollup-linux-x64-gnu
         cd apps/frontend/
         echo 'test: ${{vars.TEST_VAR}}'
         echo 'VITE_FIREBASE_API_KEY=${{secrets.VITE_FIREBASE_API_KEY}} 
               VITE_GOOGLE_MAPS_API_KEY=${{secrets.VITE_GOOGLE_MAPS_API_KEY}}  
               VITE_API_URL=${{secrets.VITE_API_URL}} 
               VITE_CDN_URL=${{secrets.VITE_CDN_URL}} 
               VITE_HOST_URL=${{secrets.VITE_HOST_URL}}' > .env
         npm run build
     
     - name: Append file to Server Nginx
       uses: appleboy/scp-action@master
       with:
         host : ${{ secrets.HOST_IP }}
         username: ${{ secrets.HOST_USERNAME }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         password: 'garageWoder_2024'
         port: 22
         script: |
            rm -rf /var/www/html/*
         source: "./apps/frontend/dist/**"
         target: "/var/www/html/"
         strip_coments: 3

      
         
         
         
