on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  # deploy Fe to server
  deploy-fe:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v4
     
     - name: Setup Node
       uses: actions/setup-node@v2
       with:
         node-version: '20.x'

     - name: Build FE App
       run: | 
         npm i
         npm i @rollup/rollup-linux-x64-gnu
         cd apps/frontend/
         echo 'VITE_FIREBASE_API_KEY=${{vars.VITE_FIREBASE_API_KEY}} 
               VITE_GOOGLE_MAPS_API_KEY=${{vars.VITE_GOOGLE_MAPS_API_KEY}}  
               VITE_API_URL=${{vars.VITE_API_URL}} 
               VITE_CDN_URL=${{vars.VITE_CDN_URL}} 
               VITE_HOST_URL=${{vars.VITE_HOST_URL}}' > .env
         npm run build
     
     - name: Append file to Server Nginx
       uses: appleboy/scp-action@master
       with:
         host : ${{vars.HOST_IP}}
         username: ${{secrets.HOST_USERNAME}}
         key: ${{vars.SSH_PRIVATE_KEY}}
         port: 22
         source: "./apps/frontend/dist/**"
         target: "/var/www/html/"
         strip_coments: 3

      
         
         
         
